from turtle import *
tela = Screen()
cao = Turtle()
cao.color("red")
cao.left(90)
cao.forward(90)
cao.right(180)
cao.forward(90)
gato = Turtle()
gato.color("blue")
gato.right(180)
gato.forward(90)
gato.right(180)
gato.forward(90)
lebre = Turtle()
lebre.color("green")
lebre.forward(90)
lebre.right(180)
lebre.forward(90)
pangolim = Turtle()
pangolim.color("yellow")
pangolim.right(90)
pangolim.forward(90)
pangolim.right(180)
pangolim.forward(90)